catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.3
  vitest: 5.0.2
  vite-plus: ^0.3.3
  typescript: ^7.0.2
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
packages:
  - packages/*
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
